# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='hcb',
    version='0.1.0',
    description='HCB stands for "Header Code Bad". It\'s a tool to automatically move code from header files to corresponding source files.',
    python_requires='==3.*,>=3.6.0',
    author='Tamás Szelei',
    author_email='szelei.t@gmail.com',
    license='MIT',
    packages=["hcb", "hcb.clang"],
    package_data={},
    # install_requires=['clang==6.0.0.2'],
    # extras_require={'dev': ['pytest==5.*,>=5.4.2']},
    entry_points={
        "console_scripts": ["hcb=hcb.main:main"]
    }
)
